<a href="https://colab.research.google.com/github/rvthe-elegant/deep_learning/blob/assignment_1/ASSIGN1_ACTIVITY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(7+8)

15


In [ ]:
pip install googletrans

     |████████████████████████████████| 61kB 3.1MB/s 
     |████████████████████████████████| 51kB 4.3MB/s 
     |████████████████████████████████| 1.0MB 6.5MB/s 
     |████████████████████████████████| 61kB 6.4MB/s 
     |████████████████████████████████| 71kB 5.8MB/s 
     |████████████████████████████████| 102kB 7.3MB/s 
  Created wheel for googletrans: filename=googletrans-3.0.0-cp36-none-any.whl size=15736 sha256=89449d9516f880bda175d830ab9054e83adbba3c00ecf77df36cfb002f4506dc
  Stored in directory: /root/.cache/pip/wheels/28/1a/a7/eaf4d7a3417a0c65796c547cff4deb6d79c7d14c2abd29273e
  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7667 sha256=93189516de54dcc7941b13c095b3f4ae31c74c20cef9cc0588effdec3ff9da65
  Stored in directory: /root/.cache/pip/wheels/a5/7d/68/1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de
Successfully built googletrans contextvars


In [ ]:
pip install google_trans_new

In [ ]:
from google_trans_new import google_translator  
translator = google_translator()  
translate_text = translator.translate('สวัสดีจีน',lang_tgt='en')  
print(translate_text)

Hello china 


In [ ]:
f = open("C:\Users\DELL\Desktop\translate.txt", 'r')
if f.mode == 'r':
    text = f.read()
print(text)

SyntaxError: ignored

In [ ]:
!nvidia-smi

Fri Feb  5 07:00:40 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P0    25W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import  numpy as np
import pandas as pd

In [ ]:
 class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):
        #return (x >= 0).astype(np.float32)
        return 1 if x >= 0 else 0
 
    def predict(self, x):
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
 
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)
                y = self.predict(x)
                e = d[i] - y
                self.W = self.W + self.lr * e * x


if __name__ == '__main__':
    X = np.array([
        [2, 3],
        [5, 6],
        [8, 9]
    ])
    d = np.array([0, 1, 1])
 
    perceptron = Perceptron(input_size=2)
    perceptron.fit(X, d)
    print(perceptron.W)

[-9.  6. -3.]


In [ ]:
# Python program to implement a 
# single neuron neural network 

# import all necessery libraries 
from numpy import exp, array, random, dot, tanh 

# Class to create a neural 
# network with single neuron 
class NeuralNetwork(): 
	
	def __init__(self): 
		
		# Using seed to make sure it'll 
		# generate same weights in every run 
		random.seed(1) 
		
		# 3x1 Weight matrix 
		self.weight_matrix = 2 * random.random((3, 1)) - 1

	# tanh as activation function 
	def tanh(self, x): 
		return tanh(x) 

	# derivative of tanh function. 
	# Needed to calculate the gradients. 
	def tanh_derivative(self, x): 
		return 1.0 - tanh(x) ** 2

	# forward propagation 
	def forward_propagation(self, inputs): 
		return self.tanh(dot(inputs, self.weight_matrix)) 
	
	# training the neural network. 
	def train(self, train_inputs, train_outputs, 
							num_train_iterations): 
								
		# Number of iterations we want to 
		# perform for this set of input. 
		for iteration in range(num_train_iterations): 
			output = self.forward_propagation(train_inputs) 

			# Calculate the error in the output. 
			error = train_outputs - output 

			# multiply the error by input and then 
			# by gradient of tanh funtion to calculate 
			# the adjustment needs to be made in weights 
			adjustment = dot(train_inputs.T, error *
							self.tanh_derivative(output)) 
							
			# Adjust the weight matrix 
			self.weight_matrix += adjustment 

# Driver Code 
if __name__ == "__main__": 
	
	neural_network = NeuralNetwork() 
	
	print ('Random weights at the start of training') 
	print (neural_network.weight_matrix) 

	train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]) 
	train_outputs = array([[0, 1, 1, 0]]).T 

	neural_network.train(train_inputs, train_outputs, 10000) 

	print ('New weights after training') 
	print (neural_network.weight_matrix) 

	# Test the neural network with a new situation. 
	print ("Testing network on new examples ->") 
	print (neural_network.forward_propagation(array([1, 0, 0]))) 


Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New weights after training
[[5.39428067]
 [0.19482422]
 [0.34317086]]
Testing network on new examples ->
[0.99995873]


## **RAHUL LAXMAN VASANAD**
## **20MAI0038**

In [ ]:
#Creating Input matrix
import numpy as np

values = ([2,3],[5,6],[8,9])
print("Training input values without Bias\n", values)

Training input values without Bias
 ([2, 3], [5, 6], [8, 9])


In [ ]:
#Adding Bias to the input values
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)

Training input values with bias in it
 [[-1  2  3]
 [-1  5  6]
 [-1  8  9]]


In [ ]:
#Creating random weights
m=3     #number of elements in each row of inputs
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)

Initial random weights
 [[-0.4082175 ]
 [-0.49350829]
 [-0.42478525]]


In [ ]:
#Target values Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)

Training data target values are
 ([0], [1], [1])


In [ ]:
#Method for updating weights
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights

In [ ]:
#Creating Methods for Learning
def  prediction (inputs, weights, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights

In [ ]:
#Training our model and extracting stable weights
iterations = 4
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)


Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Trained Weights
 [[-0.16765962]
 [ 1.25099204]
 [ 1.00857987]]


In [ ]:
#Testing new data
def perceptronPredict(weights, newInput):
    activation = np.dot(newInput, weights)
    activation = np.where(activation>0, 1, 0)
    print(activation)


newInput = ([-1.0, 7,8])
perceptronPredict(weights, newInput)

[1]
